# Generated by Django 4.2.6 on 2023-10-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_types_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('0', 'Guitarras'), ('1', 'Bajos'), ('2', 'Teclados y Pianos'), ('3', 'Baterias y Percusión'), ('4', 'Instrumentos de Viento'), ('5', 'Accesorios')], default='0', max_length=1),
        ),
    ]
