# Generated by Django 4.2.6 on 2023-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('0', 'Guitarras'), ('1', 'Bajos'), ('2', 'Teclados y Pianos'), ('3', 'Baterias y Percusión'), ('4', 'Instrumentos de Viento'), ('5', 'Accesorios')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.CharField(choices=[('0', 'Cuerdas'), ('2', 'Teclados y Pianos'), ('3', 'Baterias y Percusión'), ('5', 'Accesorios')], default='0', max_length=1),
        ),
    ]
