# Generated by Django 4.2.6 on 2023-10-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_main_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
