# Generated by Django 4.2.6 on 2023-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type_tool',
            field=models.CharField(choices=[('0', 'Guitarras')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('0', 'Guitarras'), ('1', 'Bajos'), ('2', 'Teclados y Pianos'), ('3', 'Baterias y Percusión'), ('4', 'Instrumentos de Viento'), ('5', 'Accesorios')], default='0', max_length=1),
        ),
    ]
