# Generated by Django 4.2.6 on 2023-10-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_type_tool_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type_tool',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(choices=[('0', 'Guitarras'), ('2', 'Teclados y Pianos'), ('3', 'Baterias y Percusión'), ('4', 'Viento'), ('5', 'Accesorios')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('0', 'Cuerdas'), ('2', 'Teclados y Pianos'), ('3', 'Baterias y Percusión'), ('4', 'Viento'), ('5', 'Accesorios')], default='0', max_length=1),
        ),
    ]
