# Generated by Django 4.2.6 on 2023-10-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_category_type_tool_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.CharField(choices=[('0', 'Guitarras'), ('1', 'Bajos'), ('2', 'Violines'), ('3', 'Teclados Electrónicos'), ('4', 'Pianos Digitales'), ('5', 'Sintetizadores'), ('6', 'Baterías Electrónicas'), ('7', 'Baterías Acústicass'), ('8', 'Percusión Étnica')], default='0', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
