# Generated by Django 4.2.6 on 2023-10-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_category_subcategory_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
    ]
