# Generated by Django 4.2.6 on 2023-10-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
